version: '3.1'

services:
  otusdb:
    image: mysql:8.0.15
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command: 
      --init-file /init.sql
    volumes:
      - D:/otus-dbms/Shopify-Product-CSVs-and-Images/CSVs:/data
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"